# Application values for DFO Party
# This chart manages Backend and Frontend which are frequently updated

# Global settings
global:
  environment: production
  domain: localhost

# Backend Configuration
backend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: kimrie92/dfo-party-backend
    tag: "latest"
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Health check configuration
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  # Environment variables
  env:
    - name: DB_HOST

      value: "df-party-infrastructure-mariadb"
    - name: DB_PORT
      value: "3306"
    - name: DB_NAME
      value: "dnfp"
    - name: DB_USERNAME
      value: "root"
    - name: DB_PASSWORD
      value: "dfparty-root-password"
    - name: SHOW_SQL
      value: "false"
    - name: DF_API_BASE_URL
      value: "https://api.neople.co.kr/df"
    - name: DF_API_RATE_LIMIT
      value: "100"
    - name: DF_API_RATE_LIMIT_WINDOW
      value: "60000"
  
  # Init container for waiting MariaDB
  initContainers:
    - name: wait-for-mariadb
      image: busybox:1.35
      command: ['sh', '-c', 'until nc -z df-party-infrastructure-mariadb 3306; do echo waiting for mariadb; sleep 2; done;']

# Frontend Configuration
frontend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: kimrie92/dfo-party-frontend
    tag: "latest"
    pullPolicy: Always
  
  service:
    type: ClusterIP
    port: 80
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
