# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: development
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/dnfp_dev?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:dfparty}
    password: ${DB_PASSWORD:dfparty-password}
  
  jpa:
    hibernate:
      ddl-auto: update  # 개발환경에서는 스키마 자동 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Development-specific logging
logging:
  level:
    com.dfparty.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development mock settings
app:
  mock:
    enabled: true  # 개발환경에서는 Mock 활성화
