# Server Configuration
server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dnfp}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:dfparty}
    password: ${DB_PASSWORD:dfparty-password}
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate  # 운영환경에서는 validate, 개발환경에서는 update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  
  sql:
    init:
      mode: never  # MariaDB 초기화는 Helm 차트에서 담당
  
  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false
  
  devtools:
    restart:
      enabled: true
      quiet-period: 1s
      poll-interval: 2s
      trigger-file: .trigger
    livereload:
      enabled: true

# Environment-specific database configuration
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/dnfp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:dfparty}
    password: ${DB_PASSWORD:dfparty-password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Development DFO API settings
df:
  api:
    base-url: https://api.neople.co.kr/df
    key: ${DF_API_KEY:your_dfo_api_key_here}
    rate-limit: 100
    rate-limit-window: 60000

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/dnfp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:dfparty}
    password: ${DB_PASSWORD:dfparty-password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Production DFO API settings
df:
  api:
    base-url: https://api.neople.co.kr/df
    key: ${DF_API_KEY:your_dfo_api_key_here}
    rate-limit: 100
    rate-limit-window: 60000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

# Logging Configuration
logging:
  level:
    com.dfparty.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# DFO API Configuration (기본값 - 프로필별 설정으로 오버라이드됨)



# Dundam Configuration
dundam:
  scheduler:
    enabled: false  # 던담 스케줄러 동기화 활성화/비활성화 (기본값: false)
  crawling:
    enabled: false  # 던담 크롤링 기능 활성화/비활성화 (기본값: false)
  sync:
    interval: 60000  # 동기화 간격 (밀리초, 기본값: 1분)
    batch-size: 1    # 배치 크기 (기본값: 1개씩)

