# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: development
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/dnfp_dev?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:dfparty}
    password: ${DB_PASSWORD:dfparty-password}
  
  jpa:
    hibernate:
      ddl-auto: update  # 개발환경에서는 스키마 자동 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Development-specific logging
logging:
  level:
    com.dfparty.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



# Development DFO API settings
df:
  api:
    base-url: https://api.neople.co.kr/df
    key: ${DF_API_KEY:your_dfo_api_key_here}
    rate-limit: 100
    rate-limit-window: 60000

# Development Dundam settings (기본값: false)
dundam:
  scheduler:
    enabled: false  # 개발환경에서도 기본적으로 던담 동기화 비활성화
  crawling:
    enabled: false  # 개발환경에서도 기본적으로 던담 크롤링 비활성화
  sync:
    interval: 60000
    batch-size: 1
