apiVersion: v1
kind: Secret
metadata:
  name: dfo-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.dfoApiKey | b64enc }}
