apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
