# Database Configuration
auth:
  rootPassword: "dfparty-root-password"
  database: "dnfp"
  username: "dfparty"
  password: "dfparty-password"

# Replica Configuration
replicaCount: 1

# Persistence
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessMode: ReadWriteOnce

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Security Context - 권한 문제 해결
securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
  runAsNonRoot: false  # init container가 root로 실행되어야 하므로 false로 변경

# Init Container - 데이터 디렉토리 권한 설정
initContainers:
  - name: init-mariadb-data
    image: busybox:1.35
    command: ['sh', '-c', 'chown -R 999:999 /var/lib/mysql && chmod -R 755 /var/lib/mysql']
    volumeMounts:
      - name: data
        mountPath: /var/lib/mysql
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: true

# Metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: false

# Environment variables
env:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "mariadb-secret"
        key: mariadb-root-password
  - name: MYSQL_DATABASE
    value: "dnfp"
  - name: MYSQL_USER
    value: "dfparty"
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "mariadb-secret"
        key: mariadb-password
  - name: MYSQL_ROOT_HOST
    value: "%"
  - name: MYSQL_TCP_PORT
    value: "3306"
  - name: MYSQL_PORT
    value: "3306"

# Service Configuration
service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

# Container Configuration
image:
  repository: mariadb
  tag: "11.8.3"
  pullPolicy: IfNotPresent

# Port Configuration
containerPort: 3306
hostPort: 0

# Health Checks
livenessProbe:
  tcpSocket:
    port: 3306
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 3306
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 1

# Volume Mounts
volumeMounts:
  - name: init-scripts
    mountPath: /docker-entrypoint-initdb.d
    readOnly: true
  - name: data
    mountPath: /var/lib/mysql

# Volumes
volumes:
  - name: init-scripts
    configMap:
      name: "dfo-party-mariadb-init"
  - name: data
    persistentVolumeClaim:
      claimName: "dfo-party-mariadb-data"

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node Selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# ServiceAccount Configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
